# Least-squares approach to risk parity
Bai X, Scheinberg K, Tutuncu R (2016) Least-squares approach to risk parity in portfolio selection. Quantitative Finance 16:357–376.

### 2.3 Risk parity problem: Least-squares model with general bounds and fixed theta

Implement function 16 to find weight of asset with the general bound [a,b]

#### Function(16)：

$$\min_{x}{\sum_{i=1,j=1}^n (x_i(\sum x)_i-x_j(\sum x)_j)^2}$$

s.t.
$$a_i\leq x_i\leq b_i $$

$$\sum_{i=1}^n x_i=1$$

### 2.3 Risk parity problem: Least-squares model with general bounds and variable theta
Implement function 17 to find weight of asset with the general bound [a,b]

#### Function(17)：

$$\min_{x,\theta}{\sum_{i=1}^n (x_i(\sum x)_i-\theta)^2}$$

s.t.
$$a_i\leq x_i\leq b_i $$

$$\sum_{i=1}^n x_i=1$$

### 4.1 Extended least-squares models: Minimum variance with risk parity

Implement function 28 to find the solution with minimum variance

#### Function(28):

$$\min_{x,\theta}{\sum_{i=1}^n (x_i(\sum x)_i-\theta)^2+\rho x^\mathsf{T} \sum x}$$

s.t.
$$a_i\leq x_i\leq b_i $$

$$\sum_{i=1}^n x_i=1$$

#### Algorithm 1: Sequential min-variance risk parity algorithm
1. Choose $\rho^0$ > 0, β ∈ (0, 1), ε > 0 and $x^0$;
2. for k = 0, 1,...

    If  $\rho^k$ ≥ ε, then find $x^{k+1}$ that solves (28) with $\rho$ = $\rho^k$
using $x^k$ as a starting point.

      Then set $\rho$ = $\rho^k$$\rho^{k+1}$ :=  $\rho^k$ β, CONTINUE.

    Else, find $x^{k+1}$ that solves (28) ρ = 0 using $x^k$ as a
starting point. EXIT.

## Implementation: RiskParity2

![jupyter](./framework.jpg)

## Examples

In [1]:
import sys
import numpy as np
sys.path.insert(sys.path.index('')+1, '/Users/liyafen/Documents/GitHub/pyfeng')
import pyfeng as pf
import pyfeng.ex as pfex
import warnings
warnings.filterwarnings("ignore")

In [2]:
cov = np.array([
        [94.868, 33.750, 12.325, -1.178, 8.778],
        [33.750, 445.642, 98.955, -7.901, 84.954],
        [12.325, 98.955, 117.265, 0.503, 45.184],
        [-1.178, -7.901, 0.503, 5.460, 1.057],
        [8.778, 84.954, 45.184, 1.057, 34.126]
    ]) / 10000
m = pfex.RiskParity2(cov=cov)

2.3 Risk parity problem: Least-squares model with general bounds and fixed theta

In [3]:
#paper result:[0.125; 0.047; 0.083; 0.613; 0.132] 
weight = m.general_risk_parity_with_fixed_theta(a=-1,b=2)
print(weight)

[0.12450587 0.04666161 0.08328325 0.61329749 0.13225179]


2.3 Risk parity problem: Least-squares model with general bounds and variable theta

In [4]:
# With variable theta and general bounds, there will be multiple solutions for the riskparity problem.
# Results of optimization by from scipy.optimize import minimize is not reliable. 
# That's why we need Algorithm1 in 4.1.
weight = m.general_risk_parity_with_variable_theta(a=-1,b=2)
print(weight)
weight = m.general_risk_parity_with_variable_theta(a=0.05,b=0.35)
print(weight)

[0.20003216 0.19990448 0.20002062 0.20001948 0.20002326]
[0.20003216 0.19990448 0.20002062 0.20001948 0.20002326]


4.1 Extended least-squares models: Minimum variance with risk parity

In [5]:
#paper result: [0.050; 0.006; 0.000; 0.862; 0.082] 
weight = m.minimum_variance_risk_parity_extended_least_square(rho=1000, beta=0.01, tol=1e-6, itreation_max=100,a=0, b=1)
print(weight)

[5.02145670e-02 6.43437760e-03 3.98107614e-08 8.61788507e-01
 8.15625088e-02]


In [6]:
#paper result: [0.200; 0.050; 0.050; 0.350; 0.350] 
weight = m.minimum_variance_risk_parity_extended_least_square(rho=1000, beta=0.01, tol=1e-6, itreation_max=100,a=0.05, b=0.35)
print(weight)

[0.19999981 0.05       0.05000133 0.35       0.34999885]
