In [5]:
import sys
import numpy as np
sys.path.insert(sys.path.index('')+1, '/Users/liyafen/Documents/GitHub/pyfeng')
import pyfeng as pf
import pyfeng.ex as pfex

In [6]:
pf

<module 'pyfeng' from '/Users/liyafen/Documents/GitHub/pyfeng/pyfeng/__init__.py'>

# Example 1

In [7]:
cov = np.array([
        [94.868, 33.750, 12.325, -1.178, 8.778],
        [33.750, 445.642, 98.955, -7.901, 84.954],
        [12.325, 98.955, 117.265, 0.503, 45.184],
        [-1.178, -7.901, 0.503, 5.460, 1.057],
        [8.778, 84.954, 45.184, 1.057, 34.126]
    ]) / 10000
m = pfex.RiskParity2(cov=cov)

In [8]:
weight = m.general_risk_parity_with_fixed_theta()
print(weight)
# [0.12450587 0.04666161 0.08328325 0.61329749 0.13225179]

[0.12450587 0.04666161 0.08328325 0.61329749 0.13225179]


In [9]:
weight = m.general_risk_parity_with_variable_theta()
print(weight)
# [0.20003216 0.19990448 0.20002062 0.20001948 0.20002326]

[0.20003216 0.19990448 0.20002062 0.20001948 0.20002326]


In [11]:
weight = m.minimum_variance_risk_parity_extended_least_square(rho=1000, beta=0.01, tol=1e-6, itreation_max=100,a=-1,b=2)
print(weight)
#[ 0.05027209  0.00553736 -0.01230498  0.85650904  0.09998649]

[ 0.05027209  0.00553736 -0.01230498  0.85650904  0.09998649]


# Example 2

In [12]:
cov = np.array([
        [1,-0.9,0.6],
        [-0.9,1.0,-0.2],
        [0.6,-0.2,4.0]
    ])

m = pfex.RiskParity2(cov=cov)

In [14]:
weight = m.general_risk_parity_with_fixed_theta(a=-1,b=2)
print(weight)
# [0.45520246 0.4805526  0.06424494]

[0.45520246 0.4805526  0.06424494]


In [15]:
weight = m.general_risk_parity_with_variable_theta(a=-1,b=2)
print(weight)
# [0.26339982 0.19102125 0.54557893]

[0.26339982 0.19102125 0.54557893]


In [16]:
weight = m.minimum_variance_risk_parity_extended_least_square(rho=1000, beta=0.01, tol=1e-6, itreation_max=100, a=-1,
                                                           b=2)
print(weight)
#[ 0.53233682  0.51447136 -0.04680817]

[ 0.53233682  0.51447136 -0.04680817]
