# Basket option implementation with Bachelier model CV

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pyfeng as pf

#import option_models as opt
from option_models import basket

In [3]:
# A trivial test case 1: 
# one asset have 100% weight (the others zero)
# the case should be equivalent to the BSM or Normal model price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.array([1, 0, 0, 0])
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 120

In [4]:
cor_m

array([[1. , 0.5, 0.5, 0.5],
       [0.5, 1. , 0.5, 0.5],
       [0.5, 0.5, 1. , 0.5],
       [0.5, 0.5, 0.5, 1. ]])

In [5]:
print(weights)

np.random.seed(123456)
price_basket = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, bsm=False)
print(price_basket)

[1 0 0 0]
26.570984651213593


In [6]:
# Compare the price to normal model formula

norm1 = pf.Norm(sigma=40)
price_norm = norm1.price(strike, spot[0], texp, cp=1)
print(price_basket, price_norm)

26.570984651213593 26.57084595787051


In [7]:
# A trivial test case 2
# all assets almost perfectly correlated:
# the case should be equivalent to the BSM or Normal model price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.ones(4) * 0.25
divr = np.zeros(4)
intr = 0
cor_m = 0.0001*np.identity(4) + 0.9999*np.ones((4,4))
texp = 5
strike = 120

print( cor_m )

np.random.seed(123456)
price_basket = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, bsm=False)
print(price_basket, price_norm)

[[1.     0.9999 0.9999 0.9999]
 [0.9999 1.     0.9999 0.9999]
 [0.9999 0.9999 1.     0.9999]
 [0.9999 0.9999 0.9999 1.    ]]
26.57211110181949 26.57084595787051


In [8]:
# A full test set for basket option with exact price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.ones(4) * 0.25
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 100
price_exact = 28.0073695

In [9]:
weights, cor_m

(array([0.25, 0.25, 0.25, 0.25]),
 array([[1. , 0.5, 0.5, 0.5],
        [0.5, 1. , 0.5, 0.5],
        [0.5, 0.5, 1. , 0.5],
        [0.5, 0.5, 0.5, 1. ]]))

In [10]:
price_basket = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, bsm=False)
print(price_basket, price_exact)

28.22782882893394 28.0073695


# [To Do] Basket option implementation based on BSM model
## Write the similar test for BSM

In [21]:
price_basket = basket.basket_price_mc(strike, spot, vol, weights, texp, cor_m, bsm=True)
print(price_basket)

28.57842819648004


In [8]:
strike

120

In [9]:
spot

array([100., 100., 100., 100.])

In [10]:
vol

array([0.4, 0.4, 0.4, 0.4])

In [11]:
weights

array([0.25, 0.25, 0.25, 0.25])

In [12]:
texp

5

In [13]:
cor_m

array([[1.    , 0.9999, 0.9999, 0.9999],
       [0.9999, 1.    , 0.9999, 0.9999],
       [0.9999, 0.9999, 1.    , 0.9999],
       [0.9999, 0.9999, 0.9999, 1.    ]])

In [22]:
# A trivial test case 1: 
# one asset have 100% weight (the others zero)
# the case should be equivalent to the BSM or Normal model price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.array([1, 0, 0, 0])
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 120

print(weights)

np.random.seed(123456)
price_basket = basket.basket_price_mc(strike, spot, vol, weights, texp, cor_m, bsm=True)
price_basket

[1 0 0 0]


28.51439365199859

In [23]:
bsm1 = pf.Bsm(sigma=vol[0])
price_bsm = bsm1.price(strike, spot[0], texp, cp=1)
print(price_basket, price_bsm)

28.51439365199859 28.713486748445934


# Spread option implementation based on normal model

In [24]:
# A full test set for spread option

spot = np.array([100, 96])
vol = np.array([0.2, 0.1])
weights = np.array([1, -1])
divr = np.array([1, 1])*0.05
intr = 0.1
cor = 0.5
cor_m = np.array([[1, cor], [cor, 1]])
texp = 1
strike = 0
price_exact = 8.5132252

In [25]:
# MC price based on normal model
# make sure that the prices are similar

np.random.seed(123456)
price_spread = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, intr=intr, divr=divr, bsm=False)
print(price_spread, price_exact)

8.317680907159142 8.5132252


# Spread option implementation based on BSM model

In [40]:
# Once the implementation is finished the BSM model price should also work
price_spread = basket.basket_price_mc(
    strike, spot, vol, weights, texp, cor_m, intr=intr, divr=divr, bsm=True)
price_spread

8.535628863312969

In [41]:
# You also test Kirk's approximation
kirk = pf.BsmSpreadKirk(vol, cor=cor, divr=divr, intr=intr)
price_kirk = kirk.price(strike, spot, texp)
print(price_kirk, price_spread)

8.513225229545505 8.535628863312969


# [To Do] Complete the implementation of basket_price_norm_analytic
# Compare the MC stdev of BSM basket prices from with and without CV

In [42]:
# The basket option example from above
spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.array([1, 1, 1, 1])/4
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 120

In [62]:
### Make sure that the analytic normal price is correctly implemented
basket.basket_price_norm_analytic(strike, spot, vol*spot, weights, texp, cor_m, intr=intr, divr=divr)

forward: [100.]
vol_std: [70.71067812]
price: 19.330395569726363


19.330395569726363

In [63]:
# Run below about 100 times and get the mean and stdev

### Returns 2 prices, without CV and with CV 
price_basket = basket.basket_price_mc_cv(strike, spot, vol, weights, texp, cor_m)

forward: [100.]
vol_std: [70.71067812]
price: 19.330395569726363


In [64]:
print(price_basket)

[21.17086326 21.86693157]


In [65]:
price_basket_without_cv=[]
price_basket_with_cv =[]
for i in range(100):
    price1,price2 \
    = basket.basket_price_mc_cv(strike, spot, vol, weights, texp, cor_m)
    price_basket_without_cv.append(price1)
    price_basket_with_cv.append(price2)

In [70]:
mean_price_basket_without_cv = np.mean(price_basket_without_cv)
std_price_basket_without_cv = np.std(price_basket_without_cv)
print('mean: price_basket_without_cv:',mean_price_basket_without_cv)
print('std:  price_basket_without_cv:',std_price_basket_without_cv)


mean: price_basket_without_cv: 21.776066714273952
std:  price_basket_without_cv: 0.6218115167313097


In [71]:
mean_price_basket_with_cv = np.mean(price_basket_with_cv)
std_price_basket_with_cv = np.std(price_basket_with_cv)
print('mean: price_basket_with_cv:',mean_price_basket_with_cv)
print('std:  price_basket_with_cv:',std_price_basket_with_cv)


mean: price_basket_with_cv: 21.856906134296956
std:  price_basket_with_cv: 0.7166771505292121
